### ISSUE TITLE
Non rendering Game JFrame after Credits clicked

### ISSUE THREAD

**Issue by fan2dev** [ZzCry12/blackjack#1]
## Environment: 
 - Windows 11 VS Code Debugger
 - Production Jar

## Steps
 1. Open the game 
 2. Click on the credits button (Menu)
 3. Return to the menu ("Menu principal" Button)
 4. Click on the "Jugar" Button

## Error
Appears on a grey screen and the game is not displayed.

## Possible solution
Not Avaliable

## Other improvements
 - "esc" key to return to the menu. (Other keys like "R" to reload)
 - Margin between texts and box button in the Menu.

**Comment by ZzCry12** [comment]
Fixed.
